### ISSUE TITLE
类似项目

### ISSUE THREAD

**Issue by yaming116** [NingSo/CurlHttp#1]
[https://github.com/aloha-app/libcurldroid](https://github.com/aloha-app/libcurldroid)和这个项目有什么区别?

**Comment by NingSo** [comment]
哈哈，确是类似，我是看了 http://blog.csdn.net/yanglinjingshu/article/details/45605381 的博客之后并且当时刚好要弄底层的jni网络请求，看着这篇博客搞的。so库我编译出两套，一个轻简的一个就是博主那种。😄

**Comment by NingSo** [comment]
哈哈，确是类似，我是看了 http://blog.csdn.net/yanglinjingshu/article/details/45605381 的博客之后并且当时刚好要弄底层的jni网络请求，看着这篇博客搞的。so库我编译出两套，一个轻简的一个就是博主那种。😄 @yaming116
